### ISSUE TITLE
Automatic acceptance of ssh keys 

### ISSUE THREAD

**Issue by CriptKee** [Fazmin/MultiSSH-command-deploy#1]
is there a way of accepting ssh keys automatically?

**Comment by Fazmin** [comment]
To make Paramiko store any new host keys, you need to use load_system_host_keys. E.g.
`client.load_host_keys(os.path.expanduser('~/.ssh/known_hosts'))`
Check line 12.

**Comment by CriptKee** [comment]
Thanks. got it working.
